export const ALL_PET_TYPES = [
  { id: 'corgi', name: '柯基', image: '/pets/corgi.png', rarity: 'common', cost: 0, desc: '活泼好动的小短腿' },
  { id: 'shiba', name: '柴犬', image: '/pets/shiba.png', rarity: 'common', cost: 100, desc: '呆萌治愈的微笑天使' },
  { id: 'golden', name: '金毛大暖男', image: '/pets/golden.png', rarity: 'rare', cost: 300, desc: '阳光温柔的居家伴侣' },
  { id: 'rabbit', name: '垂耳兔', image: '/pets/rabbit.png', rarity: 'rare', cost: 250, desc: '毛茸茸的乖巧甜心' },
  { id: 'hamster', name: '贪吃仓鼠', image: '/pets/hamster.png', rarity: 'epic', cost: 800, desc: '脸颊塞满瓜子的胖墩' },
  { id: 'ragdoll', name: '布偶猫', image: '/pets/ragdoll.png', rarity: 'legendary', cost: 1500, desc: '拥有星辰大海般双眼的仙女' },
  { id: 'husky', name: '哈士奇', image: '/pets/husky.png', rarity: 'epic', cost: 900, desc: '拆房小能手，眼神里透着智慧(二哈)' },
  { id: 'samoyed', name: '萨摩耶', image: '/pets/samoyed.png', rarity: 'rare', cost: 600, desc: '微笑天使，治愈系白云团子' },
  { id: 'panda', name: '大熊猫', image: '/pets/panda.png', rarity: 'legendary', cost: 2000, desc: '国宝级选手，除了吃就是睡' },
  { id: 'capybara', name: '水豚', image: '/pets/capybara.png', rarity: 'legendary', cost: 1800, desc: '情绪极其稳定的精神领袖' },
  { id: 'fox', name: '小狐狸', image: '/pets/fox.png', rarity: 'rare', cost: 500, desc: '聪明伶俐的红狐，尾巴超级蓬松' },
  { id: 'koala', name: '考拉', image: '/pets/koala.png', rarity: 'epic', cost: 800, desc: '职业发呆选手，永远在睡觉的边缘徘徊' },
  { id: 'axolotl', name: '六角恐龙', image: '/pets/axolotl.png', rarity: 'epic', cost: 1100, desc: '粉嫩的水中精灵，治愈系数爆表' },
  { id: 'penguin', name: '小企鹅', image: '/pets/penguin.png', rarity: 'rare', cost: 450, desc: '来自南极的小绅士，走起路摇摇晃晃' },
  { id: 'dragon', name: '小福龙', image: '/pets/dragon.png', rarity: 'mythic', cost: 5000, desc: '传说中的吉祥神兽，能带来无尽福气' },
  { id: 'calico', name: '三花猫', image: '/pets/calico.png', rarity: 'common', cost: 200, desc: '性格灵动的招财小猫' },
  { id: 'greycat', name: '小灰猫', image: '/pets/greycat.png', rarity: 'common', cost: 150, desc: '乖巧温顺的身后跟班' },
  { id: 'cyber_dragon', name: '赛博雷龙', image: '/pets/cyber_dragon_lv1.png', rarity: 'mythic', cost: 10000, desc: '来自平行次元的数码代码聚合成的正义之龙', isEvolutionary: true },
];
